version: "3.8"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8001
    restart: always
